=== uwitec/outsideworld/trunk/SpiderProcessor/xsd/processor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/demo/"
	targetNamespace="http://www.example.org/demo/">

    <complexType name="FilterType">
    	<sequence>
    		<element name="param" type="tns:ParamType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>





    		<element name="filter" type="tns:FilterType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="element" type="tns:ElementType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
        <attribute name="name" type="string"></attribute>
        <attribute name="handler" type="string"></attribute>
    	<attribute name="description" type="string"></attribute>

    </complexType>

    <complexType name="ElementType">

    	<sequence>
    		<element name="param" type="tns:ParamType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="handler" type="string"></attribute>
    	<attribute name="collector" type="string"></attribute>
    	<attribute name="description" type="string"></attribute>
    </complexType>



    <complexType name="CollectorType">
    	<sequence>
    		<element name="param" type="tns:ParamType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>

        <attribute name="name" type="string"></attribute>
        <attribute name="handler" type="string"></attribute>
    	<attribute name="description" type="string"></attribute>
    </complexType>


    <complexType name="ProcessorsType">
    	<sequence>
            <element name="processor" type="tns:ProcessorType" maxOccurs="unbounded" minOccurs="1">
    		</element>
            <element name="processorFactory" type="tns:ProcessorFactoryType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence></complexType>

    <element name="processors" type="tns:ProcessorsType"></element>

    <complexType name="ProcessorType">
    	<sequence>
    		<element name="injector" type="tns:InjectorType"
    			maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="filter" type="tns:FilterType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="element" type="tns:ElementType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>

    		<element name="collector" type="tns:CollectorType"
    			maxOccurs="unbounded" minOccurs="1">
    		</element>

    	</sequence>

    	<attribute name="name" type="string"></attribute>

    	<attribute name="failsafe" type="boolean"></attribute>
    </complexType>

    <complexType name="ParamType">
    	<attribute name="name" type="string"></attribute>
    	<attribute name="value" type="string"></attribute>
    	<attribute name="ref" type="string"></attribute>
    </complexType>

    <attribute name="NewAttribute" type="string"></attribute>


    <complexType name="ProcessorFactoryType">
    	<sequence>
    		<element name="processor" type="tns:ProcessorType"
    			maxOccurs="1" minOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="path" type="string"></attribute>
    </complexType>

    <complexType name="InjectorType">
    	<sequence>
    		<element name="param" type="tns:ParamType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="descriptioin" type="string"></attribute>
    	<attribute name="handler" type="string"></attribute>
    </complexType>
</schema>

=== uwitec/outsideworld/trunk/SpiderProcessor/xml/processor.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:processors xmlns:tns="http://www.example.org/demo/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/demo/ processor.xsd ">
	<processor name="netease_news">
		<filter handler="regexFilter">
			<param name="regex" value=".*" />
			<param name="text" ref="html" />
			<element handler="testHandler" name="" output="true">
				<param name="" ref="" value="" />
			</element>
			<element handler="testHandler" name="" output="true">
				<param name="" ref="" value="" />
			</element>
			<output handler="">
				<param name="" ref="" value="" />
			</output>
		</filter>
	</processor>
	<processorFactory path="">
		<processor>
			<filter handler="">
				<param name="" ref="" value="" />
				<filter handler="" />
				<element handler="" name="" output="true">
					<param name="" ref="" value="" />
				</element>
			</filter>
			<element handler="" name="" output="true">
				<param name="" ref="" value="" />
			</element>
			<output handler="">
				<param name="" ref="" value="" />
			</output>
		</processor>
	</processorFactory>
</tns:processors>
